export const Questions = [
  {
    prompt: "How many years did the 100 years war last?",
    optionA: "105",
    optionB: "116",
    optionC: "104",
    optionD: "99",
    answer: "optionB",
  },
  {
    prompt: "In which year was John F. Kennedy assassinated?",
    optionA: "1963",
    optionB: "1969",
    optionC: "1965",
    optionD: "1958",
    answer: "optionA",
  },
  {
    prompt: "The Ptolemy dynasty ruled which ancient kingdom?",
    optionA: "Assyria",
    optionB: "Hittite Empire",
    optionC: "Macedon",
    optionD: "Egypt",
    answer: "optionD",
  },
  {
    prompt: "Greenland was a colony of which country until 1981?",
    optionA: "Denmark",
    optionB: "Finland",
    optionC: "Russia",
    optionD: "USA",
    answer: "optionA",
  },
  {
    prompt: "Which war took place between 1950 and 1953?",
    optionA: "Vietnam War",
    optionB: "Korean War",
    optionC: "Yugoslavian Wars",
    optionD: "Soviet-Polish War ",
    answer: "optionB",
  },
  {
    prompt: "When was Rome founded?",
    optionA: "27 AD",
    optionB: "463 AD",
    optionC: "753 BCE",
    optionD: "350 BCE ",
    answer: "optionC",
  },
  {
    prompt: "In what year did the Berlin wall fall?",
    optionA: "1953",
    optionB: "1978",
    optionC: "1990",
    optionD: "1989",
    answer: "optionD",
  },
  {
    prompt: "What was the original name of New York City?",
    optionA: "New Amsterdam",
    optionB: "Nova Scotia",
    optionC: "New Bordeaux",
    optionD: "New Oxford",
    answer: "optionA",
  },
  {
    prompt: "Who was the first king of Bosnia?",
    optionA: "Stjepan II",
    optionB: "Tvrtko I",
    optionC: "Stjepan I",
    optionD: "Kulin",
    answer: "optionB",
  },
  {
    prompt: "In which country was Josef Stalin born?",
    optionA: "Azerbaijan",
    optionB: "Ukraine",
    optionC: "Soviet Union",
    optionD: "Georgia",
    answer: "optionD",
  },
];
