export const Questions = [
  {
    prompt: "How many years did the 100 years war last?",
    optionA: "105",
    optionB: "116",
    optionC: "104",
    optionD: "99",
    answer: "optionB",
  },
  {
    prompt: "In which year was John F. Kennedy assassinated?",
    optionA: "1963",
    optionB: "1969",
    optionC: "1965",
    optionD: "1958",
    answer: "optionA",
  },
  {
    prompt: "The Ptolemy dynasty ruled which ancient kingdom?",
    optionA: "Assyria",
    optionB: "Hittite Empire",
    optionC: "Macedon",
    optionD: "Egypt",
    answer: "optionD",
  },
  {
    prompt: "Greenland was a colony of which country until 1981?",
    optionA: "Denmark",
    optionB: "Finland",
    optionC: "Russia",
    optionD: "USA",
    answer: "optionA",
  },
  {
    prompt: "Which war took place between 1950 and 1953?",
    optionA: "Vietnam War",
    optionB: "Korean War",
    optionC: "Yugoslavian Wars",
    optionD: "Soviet-Polish War ",
    answer: "optionB",
  },
];
